### ISSUE TITLE
Question on Dataset Annotation

### ISSUE THREAD

**Issue by ldkong1205** [LiDAR-Perception/LiDAR-CS#1]
Hi @LiDAR-Perception, thanks for your work. It is encouraging for the 3D domain adaptation community!

Regarding the annotation in your datasets, I would like to ask whether the point clouds have point-level labels for semantic segmentation. If there are semantic labels, what is the label mapping used? If not, will you include semantic labels? Thanks!

**Comment by fangjin-cool** [comment]
Here is what happened, this work is done while I was working at Baidu, a search engine & AI company in China. The company published a new rule for paper publication after this paper is accepted, i.e, the released code must be implemented with paddlapaddle (a deep learning framework from Baidu), and the performance should not be worse than pytorch version. But my code is with pytorch and some libs based on pytorch, for example, pytorch3d. All the baselines and my code need to be reimplemented with paddlepaddle.   It takes me a lot of time to do this, and worst of all, paddlepaddle does not support matrix multiplication in C++ API at that time,  some operators such as differential rendering and sparse convolution are hard to implement. After implementing with cuda, the inference speed is 10x slow than pytorch, let alone the performance. I finally give up after being totally exhausted.

Some 3D baseline detectors developed by paddle team are just released at [https://github.com/PaddlePaddle/Paddle3D] months ago, you may know how hard for me to develop those operators alone at that time.

Sorry for this. I am not very familiar with GitHub and do not check the issues for a long time. But I just left Baidu weeks ago, so I do not need to deal with paddlepaddle anymore. If you are still interested in this code, I will make a plan for the code release with pytorch.

I know you are angry to say this, but LiDAR-Aug is actually already been used in several autonomous driving companies as far as I know. I do hope LiDAR-Aug can benefit more research works and products. And I am glad to share more codes during research or work in the future.

Please feel free to comment if you have any concerns or ideas, I will check the issues if I am free.

**Comment by LiDAR-Perception** [comment]
Thanks for your attention, it is a good idea to have point-level labels for semantic segmentation, but that needs to annotate the whole background point cloud, which is a high cost. It is not in our scope currently. Sorry about that.
