### ISSUE TITLE
VLD-128.tar.gz000 missing from your script

### ISSUE THREAD

**Issue by jacoblambert** [LiDAR-Perception/LiDAR-CS#2]
Just a heads up your download scripts for VLS-128 starts that with `wget https://ad-apolloscape.cdn.bcebos.com/LiDAR_CS/VLD-128.tar.gz001`. Without `gz000` the data can't be extracted at all. I could manually download it without any issues.

Could you also please provide download link to the splits :)

Thanks for sharing the dataset.

**Comment by LiDAR-Perception** [comment]
Thank you very much, I have update the links.
I have upload [splits.tar.gz](https://github.com/LiDAR-Perception/LiDAR-CS/blob/main/splits.tar.gz).

**Comment by jacoblambert** [comment]
Sorry to re-open this, but I noticed you're also missing the Velodyne VLP-16 in your dl script!
`wget https://ad-apolloscape.cdn.bcebos.com/LiDAR_CS/VLD-16.tar.gz`

**Comment by LiDAR-Perception** [comment]
Thank you! I have update the link.
