### ISSUE TITLE
Additional Labels

### ISSUE THREAD

**Issue by SamuelWhitby** [LiDAR-Perception/LiDAR-CS#8]
Hi, I appreciate the work you guys have put into this dataset. It's really useful for the research I am doing. As the dataset is out of sequence, adding any additional labels is challenging; I'd like to know if you guys plan to label additional attributes, such as the ground plane or if you are willing to share the dataset in sequence. I appreciate any help you can provide.

**Comment by fangjin-cool** [comment]
> Hi, I appreciate the work you guys have put into this dataset. It's really useful for the research I am doing. As the dataset is out of sequence, adding any additional labels is challenging; I'd like to know if you guys plan to label additional attributes, such as the ground plane or if you are willing to share the dataset in sequence. I appreciate any help you can provide.

Thanks for your attention.  For the ground plane fitting, refer to the "Plane segmentation" section in https://www.open3d.org/docs/latest/tutorial/geometry/pointcloud.html .  Moreover, We may not provide sequencial data due to privacy constraints.
